site_name: Post Process Nag
repo_url: https://github.com/las-unicamp/post-processing
repo_name: las-unicamp/post-processing
edit_uri: tree/main/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css