[tool.poetry]
name = "post-process"
version = "0.1.0"
description = ""
authors = ["Renato Fuzaro Miotto <renato.fmiotto@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
